name: SAP MTA Deployment

on:
  push:
    branches:
      - main  # Değişiklikler main (ana) dalına yapıldığında çalıştır
  workflow_dispatch:  # Manuel olarak iş akışını başlatmak için

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Cloud Foundry CLI
      run: |
        sudo apt-get update
        sudo apt-get install cf-cli -y

    - name: Install MTA Build Tool
      run: npm install -g mbt

    - name: Build MTA
      run: |
        mbt build
        echo "MTA build successful"

    - name: Login to CF
      run: cf login -a https://api.cf.us10-001.hana.ondemand.com -u mevlutcan.maden@solviads.com -p M.maden37

    - name: Rdx
      run: cf help -a

    - name: Deploy MTA
      run: cf mta deploy /home/runner/work/dmTrailProject/dmTrailProject/mta_archives/dm_trail_project_0.0.1.mtar
