name: SAP MTA Deployment

on:
  push:
    branches:
      - main  # Değişiklikler main (ana) dalına yapıldığında çalıştır
  workflow_dispatch:  # Manuel olarak iş akışını başlatmak için

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Cloud Foundry CLI
      run: |
        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        sudo apt-get update
        sudo apt-get install cf-cli -y

    - name: Display CF8 Help
      run: cf8 help

    # Diğer adımları ekleyin
