name: SAP MTA Deployment

on:
  push:
    branches:
      - main  # Değişiklikler main (ana) dalına yapıldığında çalıştır
  workflow_dispatch:  # Manuel olarak iş akışını başlatmak için

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: debian:bullseye

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y wget gnupg

    - name: Install Node.js and npm
      run: |
        apt-get install -y nodejs npm

    - name: Check if npm is installed
      run: npm --version

    - name: Install Cloud Foundry CLI
      run: |
        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
        echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        apt-get update
        apt-get install -y cf-cli

    - name: Display CF Help
      run: cf help

    - name: Install MTA Build Tool
      run: npm install -g mbt

    - name: Build MTA
      run: |
        mbt build
        echo "MTA build successful"

    - name: Login to CF
      run: cf login -a https://api.cf.us10-001.hana.ondemand.com -u mevlutcan.maden@solviads.com -p M.maden37

    - name: Deploy MTA
      run: cf deploy mta /home/runner/work/dmTrailProject/dmTrailProject/mta_archives/dm_trail_project_0.0.1.mtar


    # Diğer adımları buraya ekleyin
